name: camus
base: core20
version: '0.3.0'
summary: Peer-to-peer group video chat using WebRTC.
description: |
  Camus is a group video chat server that uses WebRTC for direct peer-to-peer
  communication. Users can create public or private rooms, stream audio and
  video, share their desktops, and send text messages.

grade: stable
confinement: strict

apps:
  camus:
    command: bin/camus-wrapper
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - network

hooks:
  configure:
    plugs: [network, network-bind]

parts:
  camus:
    plugin: python
    source: .

  utilities:
    plugin: dump
    source: snap/local/utilities/

  bin:
    plugin: dump
    source: snap/local/bin/
    organize:
      '*': bin/
